---
- name: "{{ consul_role }} | check if consul backinator is installed"
  stat:
    path: "{{ consul_dir_bin }}/consul-backinator"
  register: install_result

- block:
  - name: "{{ consul_role }} | download consul backinator binary"
    unarchive:
      src: "{{ consul_backup_url }}"
      dest: /tmp
      extra_opts:
        - "--strip=2"
      remote_src: true

  - name: "{{ consul_role }} | copy consul backinator binary"
    copy:
      src: "/tmp/consul-backinator-{{ consul_backup_version }}"
      dest: "{{ consul_dir_bin }}/consul-backinator"
      remote_src: true
      mode: 0755
  when: install_result.stat.exists == False

  always:
  - name: "{{ consul_role }} | clean tmp file"
    file:
      state: absent
      path: "/tmp/consul-backinator-{{ consul_backup_version }}"

- name: "{{ consul_role }} | create consul backup schedule"
  cron:
    name: consul backup
    minute: 0
    hour: "{{ consul_backup_hour }}"
    user: "{{ consul_user }}"
    job: "{{ consul_dir_bin }}/consul-backinator backup {{ consul_backup_args }}"
