---
- name: "{{ consul_role }} | copy consul configuration file"
  copy:
    dest: "{{ consul_dir_config }}/config.json"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0600
    content: "{{ lookup('template', 'templates/config-server.json.j2') | to_nice_json }}"
  notify: consul reload
