---
- block:
  - name: "{{ consul_role }} | validate | copy consul config to /tmp"
    shell: "cp -r {{ consul_dir_config }} /tmp/consul"
    changed_when: False
    check_mode: False

  - name: "{{ consul_role }} | copy config file to /tmp"
    copy:
      dest: /tmp/consul/config.json
      owner: "{{ consul_user }}"
      group: "{{ consul_group }}"
      mode: 0600
      content: "{{ lookup('template', 'templates/config.json.j2') | to_nice_json }}"
    changed_when: False
    check_mode: False

  - name: "{{ consul_role }} | validate | validating config file"
    command: "{{ consul_dir_bin }}/consul validate /tmp/consul"
    register: validate_result
    failed_when: validate_result.rc == 1
    changed_when: False
    check_mode: False
  always:
  - name: "{{ consul_role }} | validate | clean tmp files"
    file:
      state: absent
      path: /tmp/consul
    changed_when: False
    check_mode: False

- name: "{{ consul_role }} | parse template to consul config file"
  copy:
    dest: "{{ consul_dir_config }}/config.json"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0600
    content: "{{ lookup('template', 'templates/config.json.j2') | to_nice_json }}"
  when: validate_result.rc == 0
  notify: consul reload
