---
- name: create group
  group:
    name: "{{ consul_group }}"
    state: present

- name: create user
  user:
    name: "{{ consul_user }}"
    group: "{{ consul_group }}"
    system: true
    state: present

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
  with_items:
    - "{{ consul_dir_bin }}"
    - "{{ consul_dir_config }}"
    - "{{ consul_dir_configd }}"
    - "{{ consul_dir_data }}"
    - "{{ consul_dir_run }}"

- name: install dependencies
  package:
    name: unzip
    state: present

- name: check if consul is installed
  stat:
    path: "{{ consul_dir_run }}/consul"
  register: install_result

- name: download binary
  unarchive:
    src: "{{ consul_bin_url }}"
    dest: "{{ consul_dir_bin }}"
    remote_src: true
  when: install_result.stat.exists == False

- name: create configuration
  template:
    src: "config.json.j2"
    dest: "{{ consul_dir_config }}/config.json"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0600

- name: register systemd service
  template:
    src: "consul.service.j2"
    dest: "/etc/systemd/system/consul.service"
    owner: root
    group: root
    mode: 0600

- name: enabled systemd service
  service:
    name: consul
    state: "{{ consul_systemd_state }}"
    enabled: "{{ consul_systemd_enabled }}"
