---
- name: "{{ consul_role }} | install dnsmasq"
  package:
    name: dnsmasq
    state: present

- name: "{{ consul_role }} | get dnsmasq version"
  shell: dnsmasq --version | head -n 1 | awk '{ print $ 3}'
  changed_when: False
  check_mode: False
  register: dnsmasq_version

- name: "{{ consul_role }} | enable dnsmasq service"
  service:
    name: dnsmasq
    state: started
    enabled: true

- name: "{{ consul_role }} | create dnsmasq config"
  template:
    src: dnsmasq/00-consul.j2
    dest: /etc/dnsmasq.d/00-consul
    owner: root
    group: root
    mode: 0644
  notify: restart dnsmasq
