---
- name: "{{ consul_role }} | copy consul systemd file"
  template:
    src: init/consul-systemd.j2
    dest: "/etc/systemd/system/consul-{{ consul_role }}.service"
    owner: root
    group: root
    mode: 0644
  register: systemd_unit
  when: ansible_service_mgr == "systemd"

- name: "{{ consul_role }} | copy consul init.d file"
  template:
    src: initd-service.j2
    dest: "/etc/init.d/consul-{{ consul_role }}"
    owner: root
    group: root
    mode: 0755
  when: not ansible_service_mgr == "systemd"

- name: "{{ consul_role }} | enable consul service"
  service:
    name: "consul-{{ consul_role }}"
    state: started
    enabled: true

- name: "{{ consul_role }} | reload consul systemd unit"
  systemd:
    daemon_reload: true
  when:
    - ansible_service_mgr == "systemd"
    - systemd_unit.changed
