---
- name: install dependencies
  package:
    name: "{{ consul_dependencies }}"
    state: present

- name: check if consul is installed
  stat:
    path: "{{ consul_dir_run }}/consul"
  register: install_result

- name: download binary
  unarchive:
    src: "{{ consul_bin_url }}"
    dest: "{{ consul_dir_bin }}"
    remote_src: true
    mode: 0755
  when: install_result.stat.exists == False
