---
- name: start consul
  service:
    name: "consul-{{ consul_role }}"
    state: started

- name: restart consul
  service:
    name: "consul-{{ consul_role }}"
    state: restarted

- name: reload consul
  service:
    name: "consul-{{ consul_role }}"
    state: reloaded
  when: consul_init_start

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted

- name: "daemon-reload consul"
  systemd:
    daemon_reload: true
