---
- name: consul start
  service:
    name: "consul-{{ consul_role }}"
    state: started

- name: consul restart
  service:
    name: "consul-{{ consul_role }}"
    state: restarted

- name: consul reload
  service:
    name: "consul-{{ consul_role }}"
    state: reloaded

- name: dnsmasq restart
  service:
    name: dnsmasq
    state: restarted
