---
- name: consul start
  service:
    name: consul
    state: started

- name: consul restart
  service:
    name: consul
    state: restarted

- name: consul reload
  service:
    name: consul
    state: reloaded

